### ISSUE TITLE
Biohackathon 2020 accomplishments

### ISSUE THREAD

**Issue by fgypas** [panoptes-organization/panoptes#105]
New features/bugs fixes:
- [X] Package panoptes for conda (#46 and #88 ) Credits: @agardelakos 
- [X] Add delete workflow API endpoint (#90 and #103 ) Credits: @drekoumis 
- [X]  Enhance tests for all get endpoints (#89) Credits: @agardelakos 
- [X] Enhance delete functionality from the database Credits: @drekoumis 
- [X] Fix bug when deleting nonexisting workflows from the database and then running a new workflow (#107 and #109) Credits: @drekoumis 
- [x] Easthetic changes in the workflows running (#108 and #68)
- [x] Fix bug in workflows reported on the front page (#106 and #93)
- [X] Add clean-up-database API endpoint that removes all entries from the database (#111 and #112 ) Credits: @drekoumis 

Pull request reviewing:
@gkostoulas @agardelakos @fgypas
